[package]
name = "dns-query"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.1", features = ["derive"] }
color-eyre = "0.6.2"
rand = "0.8.5"
thiserror = "1.0.40"
winnow = "0.4.6"
